### ISSUE TITLE
Enable wildcard searching for member directory and site-wide search

### ISSUE THREAD

**Issue by sgeis** [givingforum/givingforum#157]
The member directory currently doesn't allow for wildcard searching. It is NOT possible to search S* to find all foundations that start with the letter S. You can only search on the name or a portion of the name. For example, you can search for "South" or "Madison" to find the "South Madison Community Foundation" but you can't find it by just searching S*. The same holds true for searching contacts. We have a member named Tammy Slater. You can only find her by searching for "Tammy" or "Slater" or "Tammy Slater." You can't find her if you search only on a portion of her last name such as "Slat."

I think that our members and staff will benefit from the ability to perform wildcard searches. It will make it easier to find an org or contact, especially if you don't remember the full org name or the exact spelling of a contact's name. I would also like to see wildcard searching enabled for our site-wide search.

Val checked with ThinkShout and found out that Solr supports wildcard searches but that it will take some investigation and work to enable it. 

Please indicate if your RA is interested or not interested in this feature.

**Comment by vrozansky** [comment]
Is there still interest in exploring/estimating this work? If yes, please weigh in by August 10th, 2015 and we'll determine whether to move this forward or close this ticket. Thank you.

**Comment by AClay2** [comment]
PSW still interested.

**Comment by canheier** [comment]
SCG and NCG yes

**Comment by EmilyBaron** [comment]
GWP yes

**Comment by sgeis** [comment]
Indiana is still interested.

**Comment by MainePhilanthropyCenter** [comment]
MPC is interested depending on cost

**Comment by PhilOhio** [comment]
POH is still interested as well but depending on cost

**Comment by kristenruff** [comment]
PNY still interested.

**Comment by vrozansky** [comment]
There's a lot of interest in this task and there's been substantial back-and-forth with ThinkShout on this. It looks like each RA will need to revert the GF Membership Directory feature and make some adjustments in order to make this work.That's not easy to do as each RA has significantly customized their directories. So distro-wide solution for this isn't the best approach. Alternatively, we can do some tweaking of Organizational Search Index (field settings) and possibly do partial reverting of member directories on individual sites.

Assigning this ticket to our themers and will coordinate this work for each RA.Resolving this ticket for now.

@jonstahl - I'll share the process with you and your developer after we've done a few sites to make sure PNW and MIE can benefit from this work as well.
