### ISSUE TITLE
Print Receipt from Order Screen

### ISSUE THREAD

**Issue by DNTownsend** [givingforum/givingforum#176]
We’d like to add a print screen feature to the order detail screen which allows the user to print a receipt containing the PSW (or other RA) logo, order number event name(s), fee(s), user information, and method of payment. Much like this screen: https://www.diigo.com/item/image/4slxl/59pi, but themed to print without the navigation buttons, social media links, etc. 

The status should display “pending” if the option to pay by check has been selected, although, in our experience, those most in need of this feature have typically paid online using a credit card and need the receipt for reporting and backup.

Additionally, Bill suggested that the order confirmation page, which is displayed immediately following check out, be adjusted to offer a direct link to “print receipt,” linking users to this page.

**Comment by EmilyBaron** [comment]
GWP is not interested at this time.

**Comment by mtrimbach** [comment]
CNJG would be interested

**Comment by sgeis** [comment]
IPA is interested in exploring. We might also be interested in having a link to this receipt included in the order confirmation email.

**Comment by PhilOhio** [comment]
POH is interested

**Comment by jonstahl** [comment]
PNW is interested.

**Comment by vrozansky** [comment]
This was discussed at the user's group as well. Lots of interest in a simple solution, hopefully through theming a printable receipt. There was also a request to capture the type of credit card used and possibly the last 4 digits since Authorize.net receipt does not include this information.

Assigning a deadline of August 10th to this ticket in order to determine how many RAs are interested and then will work on securing an estimate. Any suggestions are welcome. Thank you.

**Comment by sgeis** [comment]
Indiana is still interested.

**Comment by MainePhilanthropyCenter** [comment]
MPC is interested depending on cost.

**Comment by kcifone** [comment]
CCP is interested if it is not high-cost

**Comment by vrozansky** [comment]
Here's the latest update from Thinkshout on this:
*************
Hi Val, this should take approximately 5-7 hours. We would need to:
-Create a new print stylesheet for the view order page to print without the navigation buttons, social media links etc.
-Update the message on the checkout complete page to say “…view or print your order…” instead of just “…view your order…"
-Update the view order page to include a “print” button that activates the browser print function.
-May also need to update the view order page to include user information and method of payment if available.
**************
I can also consult with themers on this task if the group prefers though it sounds like a distro-wide task. Please weigh in. Thank you.

**Comment by mtrimbach** [comment]
CNJG is in.

**Comment by EmilyBaron** [comment]
GWP is in as well.

**Comment by PhilOhio** [comment]
POH is interested only if cost is low

**Comment by kristenruff** [comment]
PNY is not interested.

**Comment by canheier** [comment]
SCG yes

**Comment by vrozansky** [comment]
This seems like a common add-on for all participating RAs. Nancy at TS just pushed this feature to a multi-dev site and everyone can test it there - http://rel-2752-integration.gotpantheon.com.

You can also see the screenshot here - 
![order-and-print-version](https://cloud.githubusercontent.com/assets/2983264/9237299/40ce4818-4118-11e5-927b-6616004d398a.png)

What's included:
-add a print button
-add print stylesheet
-add a pending or completed message for orders paid by check
-updated the default checkout complete message to include "view or print..."

Assuming that testing goes well and doesn't reveal any problems, this functionality will be available in the next Drupal distro release (2.7.6). Thank you for voting.

**Comment by canheier** [comment]
WRAG yes only if cost is low

**Comment by canheier** [comment]
Tested on live-integration site today and looks good to go for next release!

**Comment by mtrimbach** [comment]
How customizable is the print screen?

**Comment by vrozansky** [comment]
@mtrimbach - We need a standard layout for the distro that ThinkShout will complete and release. Then, each RA can work with themers to make some adjustments. Are you asking about stylistic adjustments or structural in terms of fields? If the latter, then we'll need to go through ThinkShout.

**Comment by mtrimbach** [comment]
A little of both but as long as it can be adjusted, I'm good with this solution.

**Comment by vrozansky** [comment]
Per our earlier request, Nancy at TS added the payment method and last 4 digits of the credit card used (if used) to the print screen. You can see the working sample at http://rel-2752a-integration.gotpantheon.com/user/148/orders/97.

**Comment by mtrimbach** [comment]
Nice addition - looks good.

**Comment by vrozansky** [comment]
Haven't received additional feedback on this, so will sign off with ThinkShout and add it to the next Drupal distro release. Thank you.
