### ISSUE TITLE
Section for Board only on website

### ISSUE THREAD

**Issue by PhilOhio** [givingforum/givingforum#180]
Is it possible to have a section on our website for our board members only to access board documents/materials? They would be the only ones who could log in and access these documents. Would that have to be a new role on their account? Not sure if this has been discussed before.

**Comment by allenlaurie** [comment]
We have board only materials on our website using a group in salesforce. Only members of the group (and administrators) have access to the materials.

[cid:image006.jpg@01D04070.2F000670]
Laurie Allen | Communications Manager
Connecticut Council for Philanthropy
860-525-5585 | lallen@CTphilanthropy.org<mailto:lallen@CTphilanthropy.org>
221 Main Street, Hartford, CT  06106

CONNECT WITH US: Website<http://www.ctphilanthropy.org/> | Facebook<http://www.facebook.com/CTphilanthropy> | Twitter<http://www.twitter.com/CTphilanthropy> | News<http://www.ctphilanthropy.org/s_ccp/sec.asp?CID=6336&DID=13845> | Blog<http://ctphilanthropynotes.org/>

[ccp1_294]

**Comment by PhilOhio** [comment]
Thanks Laurie can you share how you did that? Do you have a page and tab on your website?

. . . . . . . . . . . . . . . . . . . . . . . . .
Stacey Wilson | Member Services Associate, Digital Content | Philanthropy Ohio
37 W. Broad St., Suite 800 | Columbus, OH 43215 | phone 614.224.1344 | direct 614.914.2247
www.philanthropyohio.org<http://www.philanthropyohio.org/>

[FINAL-teal-social-facebook-circle-100x100]<http://www.facebook.com/philanthropyohio>[3teal-social-Twitter-circle-100x100]<http://www.twitter.com/philanthropyoh>[FINAL-teal-social-LinkedIn100x100]<http://www.linkedin.com/company/philanthropyohio>[FINAL-teal-social-blog-circle-100x100]<http://letstalkphilanthropy.wordpress.com/>

**Comment by allenlaurie** [comment]
Stacey,

Here is the link to Our Board page: https://www.ctphilanthropy.org/about/board

The protected Board Materials are in the side bar under Meetings. The links are visible, but they are password protected. You could have a sided bar with a “Find Board Materials” link to a protected landing page so that the list of materials is not visible.

Our board members are all members of the Salesforce group, CCP Board of Directors. In the node (page, resource, news, etc.) choose the group and only members of that group can access the node.

[cid:image001.png@01D04074.1BB0F3F0]
Call me if you have any questionsJ
[cid:image003.jpg@01D04075.BCD01850]
Laurie Allen | Communications Manager
Connecticut Council for Philanthropy
860-525-5585 | lallen@CTphilanthropy.org<mailto:lallen@CTphilanthropy.org>
221 Main Street, Hartford, CT  06106

CONNECT WITH US: Website<http://www.ctphilanthropy.org/> | Facebook<http://www.facebook.com/CTphilanthropy> | Twitter<http://www.twitter.com/CTphilanthropy> | News<http://www.ctphilanthropy.org/s_ccp/sec.asp?CID=6336&DID=13845> | Blog<http://ctphilanthropynotes.org/>

[ccp1_294]

**Comment by EmilyBaron** [comment]
Thank you for sharing this Laurie! I am trying to get GWP moving toward this and it's great to have your example to show other GWP Staff how it can work! Have you had any feedback from board members about having to go online to the website to get their documents?

**Comment by allenlaurie** [comment]
We haven’t totally given up emailing them their Board Meeting materials, but we are moving towards that.

Every March we’d update the Board “Blue Book” and make copies of the updated pages. But now all that information is online.

[cid:image006.jpg@01D0451C.78124B10]
Laurie Allen | Communications Manager
Connecticut Council for Philanthropy
860-525-5585 | lallen@CTphilanthropy.org<mailto:lallen@CTphilanthropy.org>
221 Main Street, Hartford, CT  06106

CONNECT WITH US: Website<http://www.ctphilanthropy.org/> | Facebook<http://www.facebook.com/CTphilanthropy> | Twitter<http://www.twitter.com/CTphilanthropy> | News<http://www.ctphilanthropy.org/s_ccp/sec.asp?CID=6336&DID=13845> | Blog<http://ctphilanthropynotes.org/>

[ccp1_294]

**Comment by vrozansky** [comment]
Thanks for sharing, Laurie. Current features in Drupal allow you to setup these protected committee pages already and a group of 5-6 RAs are working on the Mandrill/MailChimp update that can effectively replace the listserv functionality and also enhance the existing committee features by adding threaded email conversations to the committee page. We'll also explore other options once the default functionality rolls out later this year.

Unless there are other questions specifically on the Board committee page, I'll close the ticket (trying to clean up in advance of my call with ThinkShout). Feel free to re-open at any time. Thank you.
