### ISSUE TITLE
Anybody want a testimonial object in Salesforce?

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#189]
We've (really: the fabulous Kelley Bevans) just built a "Testimonial" object in Salesforce, designed to store awesome quotes from members and let us track where we've used them. Testimonial looks like this:

![screenshot_071315_040012_pm](https://cloud.githubusercontent.com/assets/882456/8662780/3f1893fa-2978-11e5-9faa-8bd25a9a6d0d.jpg)

Has master-detail relationship to a simple "Usage" object that looks like this:

![screenshot_071315_040102_pm](https://cloud.githubusercontent.com/assets/882456/8662798/5d72c8ac-2978-11e5-891f-74068c75c17e.jpg)

If folks are interested, we're happy to provide enough additional information for Brian to drop it into the distro. Or just implement yourself from these screenshots -- this this about 20 minutes of point-and-click "dev" work.

**Comment by EmilyBaron** [comment]
You both are amazing!!! I can probably add this using your pics, but if the group decides to have it added into the distro - even better! Not sure when it would make it to the top of my TO DO/WISH LIST! I just have a word doc of testimonials that i rotate on our website and such. Would love more of a tracking option - how do you find time to work your magic!

**Comment by mtrimbach** [comment]
Great idea.  Couple of questions about the fields in the Testimonial record. Account and Category are formula fields - what are you using for the formulas? (I would have expected Account to be a look-up and Category a picklist so I'm a bit confused over those) Also, are you using the Status field to indicate In use, Unused, Previously Used, etc.?  Thanks in advance for any additional clarification you can provide!

**Comment by microveldt** [comment]
A couple of updates on this. We changed the name of the Testimonial object to Quote because it's shorter and we don't used Salesforce's Quote object (which is all about Sales Quotes). We set account and category up as formula fields to pull the information from the Contact Record to the Quote object. The lookup is on the Quotes object. We ended up dispensing with the Category field opting instead to make a custom report type that will let us group quotes by category via relation to the Contact object.

The formula on the account field is  Organization (Text)=Contact__r.Account.Name.

Here's an updated screenshot of where we've landed on all this:


[cid:C7AE121D-8D00-4C5E-9D81-6A6976CA3BDB]


And the related Usage object:

 [cid:B756B32F-BE3B-4CE1-A5C2-B2150F3D4B03]

And here's what it looks like in use:

 [cid:F7C479B2-F48E-463B-94DA-3CAE4E55FA14]

Hope this helps.

Kelley Bevans, Communications and Database Manager
Philanthropy Northwest
kbevans@philanthropynw.org<mailto:kbevans@philanthropynw.org>
206-812-7692

**Comment by vrozansky** [comment]
The deadline for this ticket is August 10th, 2015. Please cast your on whether you'd like this to be added to our common SF package or prefer to re-create this independently from the screenshots/instructions above. Thank you.

**Comment by kimsnipes** [comment]
I would prefer that RAs interested in this contact PNW directly and we leave it out of the common SF package. .

**Comment by agoldhagen** [comment]
I agree with Kim. PNY has no need for this at the moment.

**Comment by EmilyBaron** [comment]
I agree with Kim - sounds like something we can add with the help of PNW if needed.

**Comment by vrozansky** [comment]
Thanks for your comments. @dbradyforum - let's add this to our Wiki and resolve this ticket. PNW folks can assist RAs that are interested in tracking testimonials. Thank you.

**Comment by mtrimbach** [comment]
CNJG already added to Salesforce with modifications for their own use of this object. Adding to the Wiki is a great idea.

**Comment by sgeis** [comment]
Indiana likes the idea of adding this to the Wiki and closing the ticket.

**Comment by AClay2** [comment]
PSW is fine with adding to Wiki and allowing interested RAs to implement independently.

**Comment by capitalgrits** [comment]
WRAG is also fine with adding to Wiki and allowing interested RAs to implement independently.

**Comment by PhilOhio** [comment]
POH is also fine with adding to Wiki and we will implement if needed

**Comment by vrozansky** [comment]
Resolving this ticket and referencing it in our Wiki here - https://github.com/givingforum/givingforum/wiki/Salesforce:-Adding-Testimonial-Object-in-Salesforce

Thank you @jonstahl and @microveldt
